# Generated by Django 5.1.4 on 2024-12-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контактная информация', 'verbose_name_plural': 'Контактные информации'},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name': 'Сеть', 'verbose_name_plural': 'Сети'},
        ),
    ]
